# Generated by Django 5.2.17 on 2026-10-03 20:49

import animais.models
import conteudo.models
import conteudo.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(help_text='Ex.: Resgates, Marketing.', max_length=80, verbose_name='Área')),
                ('pergunta', models.CharField(help_text='Ex.: Dúvidas sobre Resgates?', max_length=150, verbose_name='Pergunta que aparece acima')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro.')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder do site sem apagar.')),
            ],
            options={
                'verbose_name': 'Área do Fale Conosco',
                'verbose_name_plural': 'Áreas do Fale Conosco',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Estatistica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(help_text='O número que aparece contando.')),
                ('prefixo', models.CharField(blank=True, help_text='Ex.: +', max_length=5)),
                ('sufixo', models.CharField(blank=True, help_text='Ex.: %', max_length=5)),
                ('titulo', models.CharField(max_length=200)),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro.')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder do site sem apagar.')),
            ],
            options={
                'verbose_name': 'Número de destaque',
                'verbose_name_plural': 'Números de destaque',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormaDeAjudar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('link_texto', models.CharField(blank=True, max_length=60, verbose_name='Texto do botão')),
                ('link_url', models.CharField(blank=True, help_text='Ex.: /animais ou https://...', max_length=300, validators=[conteudo.validators.validar_link], verbose_name='Endereço do botão')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro.')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder do site sem apagar.')),
            ],
            options={
                'verbose_name': 'Forma de ajudar',
                'verbose_name_plural': 'Formas de ajudar',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FrenteAtuacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('link_texto', models.CharField(blank=True, max_length=60, verbose_name='Texto do botão')),
                ('link_url', models.CharField(blank=True, help_text='Ex.: /fale-conosco ou https://...', max_length=300, validators=[conteudo.validators.validar_link], verbose_name='Endereço do botão')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro.')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder do site sem apagar.')),
            ],
            options={
                'verbose_name': 'Frente de atuação',
                'verbose_name_plural': 'Frentes de atuação',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PerguntaFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pergunta', models.CharField(max_length=200)),
                ('resposta', models.TextField(help_text='Para separar parágrafos, deixe uma linha em branco. **assim** deixa em negrito.')),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro.')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder do site sem apagar.')),
            ],
            options={
                'verbose_name': 'Pergunta frequente',
                'verbose_name_plural': 'Perguntas frequentes',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PontoSobre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('descricao', models.TextField()),
                ('ordem', models.PositiveIntegerField(default=0, help_text='Menor número aparece primeiro.')),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder do site sem apagar.')),
            ],
            options={
                'verbose_name': 'Ponto da seção Sobre',
                'verbose_name_plural': 'Pontos da seção Sobre',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TextoSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(max_length=100, unique=True)),
                ('pagina', models.CharField(max_length=80, verbose_name='Onde aparece')),
                ('descricao', models.CharField(max_length=200, verbose_name='O que é este texto')),
                ('valor', models.TextField(blank=True, help_text='Deixe em branco para voltar ao texto padrão do site. Dica: **assim** deixa em negrito e Enter quebra a linha.', verbose_name='Texto')),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Texto do site',
                'verbose_name_plural': 'Textos do site',
                'ordering': ['pagina', 'ordem', 'chave'],
            },
        ),
        migrations.CreateModel(
            name='ContatoEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('telefone', models.CharField(help_text='Com +55 e DDD. Ex.: +55 34 99999-9999. É o número do WhatsApp.', max_length=30, validators=[conteudo.validators.validar_telefone])),
                ('foto', models.ImageField(blank=True, help_text='Opcional (máx. 5 MB). Sem foto, o site mostra as iniciais.', upload_to=conteudo.models.upload_equipe, validators=[animais.models.validar_imagem])),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('ativo', models.BooleanField(default=True, help_text='Desmarque para esconder do site sem apagar.')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='conteudo.areacontato')),
            ],
            options={
                'verbose_name': 'Pessoa da equipe',
                'verbose_name_plural': 'Pessoas da equipe',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
