# Generated by Django 6.1.1 on 2026-09-25 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('especie', models.CharField(default='Gato', max_length=100)),
                ('idade', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='animais/')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_avaliacao', 'Em Avaliação'), ('adotado', 'Adotado')], default='disponivel', max_length=20)),
                ('descricao', models.TextField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='HistoriaAdocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_atual', models.ImageField(upload_to='historias/')),
                ('texto', models.TextField()),
                ('data_adocao', models.DateField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='animais.animal')),
            ],
            options={
                'verbose_name': 'História de Adoção',
                'verbose_name_plural': 'Histórias de Adoção',
                'ordering': ['-data_adocao'],
            },
        ),
    ]
