# Generated by Django 5.2.17 on 2026-10-03 15:44

import animais.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ['ordem', '-criado_em'], 'verbose_name': 'Animal', 'verbose_name_plural': 'Animais'},
        ),
        migrations.AddField(
            model_name='animal',
            name='ativo',
            field=models.BooleanField(default=True, help_text='Desmarque para esconder do site sem apagar.'),
        ),
        migrations.AddField(
            model_name='animal',
            name='ordem',
            field=models.PositiveIntegerField(default=0, help_text='Ordem de exibição no site. Menor número aparece primeiro.'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='descricao',
            field=models.TextField(help_text='Descrição do animal: personalidade, histórico, etc.'),
        ),
        migrations.AlterField(
            model_name='animal',
            name='especie',
            field=models.CharField(default='Gato', help_text='Espécie do animal.', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='foto',
            field=models.ImageField(help_text='Foto do animal (máx. 5 MB, formatos: JPG, PNG, GIF, WebP).', upload_to=animais.models.upload_animais, validators=[animais.models.validar_imagem]),
        ),
        migrations.AlterField(
            model_name='animal',
            name='idade',
            field=models.CharField(help_text='Idade estimada (ex: "3 meses", "2 anos").', max_length=50),
        ),
        migrations.AlterField(
            model_name='animal',
            name='nome',
            field=models.CharField(help_text='Nome do animal (ex: "Mingau", "Pipoca").', max_length=100),
        ),
        migrations.AlterField(
            model_name='animal',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_avaliacao', 'Em Avaliação'), ('adotado', 'Adotado')], default='disponivel', help_text='Status atual do animal.', max_length=20),
        ),
        migrations.AlterField(
            model_name='historiaadocao',
            name='animal',
            field=models.ForeignKey(help_text='Animal ao qual esta história pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='historias', to='animais.animal'),
        ),
        migrations.AlterField(
            model_name='historiaadocao',
            name='data_adocao',
            field=models.DateField(help_text='Data em que a adoção foi realizada.'),
        ),
        migrations.AlterField(
            model_name='historiaadocao',
            name='foto_atual',
            field=models.ImageField(help_text='Foto atual do animal no novo lar (máx. 5 MB).', upload_to=animais.models.upload_historias, validators=[animais.models.validar_imagem]),
        ),
        migrations.AlterField(
            model_name='historiaadocao',
            name='texto',
            field=models.TextField(help_text='Texto da história de adoção.'),
        ),
    ]
